from __future__ import annotations

SOURCE_FAMILY_PLD = "PLD"
SOURCE_FAMILY_BOROUGH_REGISTER = "BOROUGH_REGISTER"
SOURCE_FAMILY_PRIOR_APPROVAL = "PRIOR_APPROVAL"
SOURCE_FAMILY_BROWNFIELD = "BROWNFIELD"
SOURCE_FAMILY_POLICY = "POLICY_LAYER"
SOURCE_FAMILY_CONSTRAINT = "PLANNING_DATA_CONSTRAINT"
SOURCE_FAMILY_FLOOD = "FLOOD"
SOURCE_FAMILY_HERITAGE_ARTICLE4 = "HERITAGE_ARTICLE4"
SOURCE_FAMILY_BASELINE_PACK = "BOROUGH_BASELINE_PACK"

MANDATORY_EXTANT_SOURCE_FAMILIES = (
    SOURCE_FAMILY_BOROUGH_REGISTER,
    SOURCE_FAMILY_PRIOR_APPROVAL,
    SOURCE_FAMILY_BROWNFIELD,
)

SUPPLEMENTAL_EXTANT_SOURCE_FAMILIES = (SOURCE_FAMILY_PLD,)

ACTIVE_PERMISSION_DECISION_TYPES = {
    "FULL_RESIDENTIAL",
    "OUTLINE_RESIDENTIAL",
    "PIP",
    "TDC",
    "PRIOR_APPROVAL_RESIDENTIAL",
    "ORDER_BASED_RESIDENTIAL",
}

ACTIVE_PERMISSION_STATUSES = {"ACTIVE", "IMPLEMENTABLE", "APPROVED"}
NON_EXCLUSIONARY_STATUSES = {"LAPSED", "EXPIRED", "WITHDRAWN", "REFUSED", "CLOSED"}

PLANNING_LINK_DISTANCE_M = 50.0
CONSTRAINT_LINK_DISTANCE_M = 50.0

SOURCE_PRIORITY_BOROUGH_REGISTER = 100
SOURCE_PRIORITY_PLD = 50
