from enum import StrEnum


class JobStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    DEAD = "DEAD"


class JobType(StrEnum):
    MANUAL_URL_SNAPSHOT = "MANUAL_URL_SNAPSHOT"
    CSV_IMPORT_SNAPSHOT = "CSV_IMPORT_SNAPSHOT"
    LISTING_SOURCE_RUN = "LISTING_SOURCE_RUN"
    LISTING_CLUSTER_REBUILD = "LISTING_CLUSTER_REBUILD"
    SITE_BUILD_REFRESH = "SITE_BUILD_REFRESH"
    SITE_LPA_LINK_REFRESH = "SITE_LPA_LINK_REFRESH"
    SITE_TITLE_LINK_REFRESH = "SITE_TITLE_LINK_REFRESH"
    PLD_INGEST_REFRESH = "PLD_INGEST_REFRESH"
    BOROUGH_REGISTER_INGEST = "BOROUGH_REGISTER_INGEST"
    SITE_PLANNING_ENRICH = "SITE_PLANNING_ENRICH"
    SITE_EXTANT_PERMISSION_RECHECK = "SITE_EXTANT_PERMISSION_RECHECK"
    SOURCE_COVERAGE_REFRESH = "SOURCE_COVERAGE_REFRESH"


class SourceFreshnessStatus(StrEnum):
    FRESH = "FRESH"
    STALE = "STALE"
    UNKNOWN = "UNKNOWN"


class SourceParseStatus(StrEnum):
    PENDING = "PENDING"
    PARSED = "PARSED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class ConnectorType(StrEnum):
    MANUAL_URL = "MANUAL_URL"
    CSV_IMPORT = "CSV_IMPORT"
    PUBLIC_PAGE = "PUBLIC_PAGE"


class ComplianceMode(StrEnum):
    MANUAL_ONLY = "MANUAL_ONLY"
    CSV_ONLY = "CSV_ONLY"
    COMPLIANT_AUTOMATED = "COMPLIANT_AUTOMATED"
    BLOCKED = "BLOCKED"


class ListingType(StrEnum):
    LAND = "LAND"
    LAND_WITH_BUILDING = "LAND_WITH_BUILDING"
    GARAGE_COURT = "GARAGE_COURT"
    REDEVELOPMENT_SITE = "REDEVELOPMENT_SITE"
    UNKNOWN = "UNKNOWN"


class PriceBasisType(StrEnum):
    GUIDE_PRICE = "GUIDE_PRICE"
    ASKING_PRICE = "ASKING_PRICE"
    OFFERS_OVER = "OFFERS_OVER"
    OFFERS_IN_EXCESS_OF = "OFFERS_IN_EXCESS_OF"
    PRICE_ON_APPLICATION = "PRICE_ON_APPLICATION"
    AUCTION_GUIDE = "AUCTION_GUIDE"
    UNKNOWN = "UNKNOWN"


class ListingStatus(StrEnum):
    LIVE = "LIVE"
    UNDER_OFFER = "UNDER_OFFER"
    AUCTION = "AUCTION"
    SOLD_STC = "SOLD_STC"
    WITHDRAWN = "WITHDRAWN"
    UNKNOWN = "UNKNOWN"


class DocumentType(StrEnum):
    BROCHURE = "BROCHURE"
    MAP = "MAP"
    CSV_EXPORT = "CSV_EXPORT"
    UNKNOWN = "UNKNOWN"


class DocumentExtractionStatus(StrEnum):
    NOT_ATTEMPTED = "NOT_ATTEMPTED"
    EXTRACTED = "EXTRACTED"
    FAILED = "FAILED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class ListingClusterStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SINGLETON = "SINGLETON"


class GeomSourceType(StrEnum):
    SOURCE_POLYGON = "SOURCE_POLYGON"
    SOURCE_MAP_DIGITISED = "SOURCE_MAP_DIGITISED"
    TITLE_UNION = "TITLE_UNION"
    ANALYST_DRAWN = "ANALYST_DRAWN"
    APPROXIMATE_BBOX = "APPROXIMATE_BBOX"
    POINT_ONLY = "POINT_ONLY"


class GeomConfidence(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INSUFFICIENT = "INSUFFICIENT"


class SiteStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    INSUFFICIENT_GEOMETRY = "INSUFFICIENT_GEOMETRY"


class SiteMarketEventType(StrEnum):
    LISTING_EVIDENCE = "LISTING_EVIDENCE"


class SourceCoverageStatus(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    MISSING = "MISSING"
    UNKNOWN = "UNKNOWN"


class EligibilityStatus(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
    ABSTAIN = "ABSTAIN"


class ExtantPermissionStatus(StrEnum):
    ACTIVE_EXTANT_PERMISSION_FOUND = "ACTIVE_EXTANT_PERMISSION_FOUND"
    NO_ACTIVE_PERMISSION_FOUND = "NO_ACTIVE_PERMISSION_FOUND"
    NON_MATERIAL_OVERLAP_MANUAL_REVIEW = "NON_MATERIAL_OVERLAP_MANUAL_REVIEW"
    UNRESOLVED_MISSING_MANDATORY_SOURCE = "UNRESOLVED_MISSING_MANDATORY_SOURCE"
    CONTRADICTORY_SOURCE_MANUAL_REVIEW = "CONTRADICTORY_SOURCE_MANUAL_REVIEW"


class SourceClass(StrEnum):
    AUTHORITATIVE = "AUTHORITATIVE"
    OFFICIAL_INDICATIVE = "OFFICIAL_INDICATIVE"
    MARKET = "MARKET"
    ANALYST_DERIVED = "ANALYST_DERIVED"
    MACHINE_ASSISTIVE = "MACHINE_ASSISTIVE"


class EvidencePolarity(StrEnum):
    FOR = "FOR"
    AGAINST = "AGAINST"
    UNKNOWN = "UNKNOWN"


class EvidenceImportance(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class VerifiedStatus(StrEnum):
    VERIFIED = "VERIFIED"
    UNVERIFIED = "UNVERIFIED"
    ANALYST_VERIFIED = "ANALYST_VERIFIED"


class BaselinePackStatus(StrEnum):
    DRAFT = "DRAFT"
    PILOT_READY = "PILOT_READY"
    SIGNED_OFF = "SIGNED_OFF"
    STALE = "STALE"


class AppRoleName(StrEnum):
    ANALYST = "analyst"
    REVIEWER = "reviewer"
    ADMIN = "admin"


class StorageBackend(StrEnum):
    LOCAL = "local"
    SUPABASE = "supabase"
