from enum import StrEnum


class JobStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    DEAD = "DEAD"


class JobType(StrEnum):
    MANUAL_URL_SNAPSHOT = "MANUAL_URL_SNAPSHOT"
    CSV_IMPORT_SNAPSHOT = "CSV_IMPORT_SNAPSHOT"
    LISTING_SOURCE_RUN = "LISTING_SOURCE_RUN"
    LISTING_CLUSTER_REBUILD = "LISTING_CLUSTER_REBUILD"
    SITE_BUILD_REFRESH = "SITE_BUILD_REFRESH"
    SITE_LPA_LINK_REFRESH = "SITE_LPA_LINK_REFRESH"
    SITE_TITLE_LINK_REFRESH = "SITE_TITLE_LINK_REFRESH"
    PLD_INGEST_REFRESH = "PLD_INGEST_REFRESH"
    BOROUGH_REGISTER_INGEST = "BOROUGH_REGISTER_INGEST"
    SITE_PLANNING_ENRICH = "SITE_PLANNING_ENRICH"
    SITE_EXTANT_PERMISSION_RECHECK = "SITE_EXTANT_PERMISSION_RECHECK"
    SOURCE_COVERAGE_REFRESH = "SOURCE_COVERAGE_REFRESH"
    SITE_SCENARIO_SUGGEST_REFRESH = "SITE_SCENARIO_SUGGEST_REFRESH"
    SITE_SCENARIO_GEOMETRY_REFRESH = "SITE_SCENARIO_GEOMETRY_REFRESH"
    BOROUGH_RULEPACK_SCENARIO_REFRESH = "BOROUGH_RULEPACK_SCENARIO_REFRESH"
    SCENARIO_EVIDENCE_REFRESH = "SCENARIO_EVIDENCE_REFRESH"
    HISTORICAL_LABEL_REBUILD = "HISTORICAL_LABEL_REBUILD"
    ASSESSMENT_FEATURE_SNAPSHOT_BUILD = "ASSESSMENT_FEATURE_SNAPSHOT_BUILD"
    COMPARABLE_RETRIEVAL_BUILD = "COMPARABLE_RETRIEVAL_BUILD"
    REPLAY_VERIFICATION_BATCH = "REPLAY_VERIFICATION_BATCH"
    GOLD_SET_REFRESH = "GOLD_SET_REFRESH"
    VALUATION_DATA_REFRESH = "VALUATION_DATA_REFRESH"
    VALUATION_RUN_BUILD = "VALUATION_RUN_BUILD"


class SourceFreshnessStatus(StrEnum):
    FRESH = "FRESH"
    STALE = "STALE"
    UNKNOWN = "UNKNOWN"


class SourceParseStatus(StrEnum):
    PENDING = "PENDING"
    PARSED = "PARSED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class ConnectorType(StrEnum):
    MANUAL_URL = "MANUAL_URL"
    CSV_IMPORT = "CSV_IMPORT"
    PUBLIC_PAGE = "PUBLIC_PAGE"


class ComplianceMode(StrEnum):
    MANUAL_ONLY = "MANUAL_ONLY"
    CSV_ONLY = "CSV_ONLY"
    COMPLIANT_AUTOMATED = "COMPLIANT_AUTOMATED"
    BLOCKED = "BLOCKED"


class ListingType(StrEnum):
    LAND = "LAND"
    LAND_WITH_BUILDING = "LAND_WITH_BUILDING"
    GARAGE_COURT = "GARAGE_COURT"
    REDEVELOPMENT_SITE = "REDEVELOPMENT_SITE"
    UNKNOWN = "UNKNOWN"


class PriceBasisType(StrEnum):
    GUIDE_PRICE = "GUIDE_PRICE"
    ASKING_PRICE = "ASKING_PRICE"
    OFFERS_OVER = "OFFERS_OVER"
    OFFERS_IN_EXCESS_OF = "OFFERS_IN_EXCESS_OF"
    PRICE_ON_APPLICATION = "PRICE_ON_APPLICATION"
    AUCTION_GUIDE = "AUCTION_GUIDE"
    UNKNOWN = "UNKNOWN"


class ListingStatus(StrEnum):
    LIVE = "LIVE"
    UNDER_OFFER = "UNDER_OFFER"
    AUCTION = "AUCTION"
    SOLD_STC = "SOLD_STC"
    WITHDRAWN = "WITHDRAWN"
    UNKNOWN = "UNKNOWN"


class DocumentType(StrEnum):
    BROCHURE = "BROCHURE"
    MAP = "MAP"
    CSV_EXPORT = "CSV_EXPORT"
    UNKNOWN = "UNKNOWN"


class DocumentExtractionStatus(StrEnum):
    NOT_ATTEMPTED = "NOT_ATTEMPTED"
    EXTRACTED = "EXTRACTED"
    FAILED = "FAILED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class ListingClusterStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SINGLETON = "SINGLETON"


class GeomSourceType(StrEnum):
    SOURCE_POLYGON = "SOURCE_POLYGON"
    SOURCE_MAP_DIGITISED = "SOURCE_MAP_DIGITISED"
    TITLE_UNION = "TITLE_UNION"
    ANALYST_DRAWN = "ANALYST_DRAWN"
    APPROXIMATE_BBOX = "APPROXIMATE_BBOX"
    POINT_ONLY = "POINT_ONLY"


class GeomConfidence(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INSUFFICIENT = "INSUFFICIENT"


class SiteStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    INSUFFICIENT_GEOMETRY = "INSUFFICIENT_GEOMETRY"


class SiteMarketEventType(StrEnum):
    LISTING_EVIDENCE = "LISTING_EVIDENCE"


class SourceCoverageStatus(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    MISSING = "MISSING"
    UNKNOWN = "UNKNOWN"


class EligibilityStatus(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
    ABSTAIN = "ABSTAIN"


class ExtantPermissionStatus(StrEnum):
    ACTIVE_EXTANT_PERMISSION_FOUND = "ACTIVE_EXTANT_PERMISSION_FOUND"
    NO_ACTIVE_PERMISSION_FOUND = "NO_ACTIVE_PERMISSION_FOUND"
    NON_MATERIAL_OVERLAP_MANUAL_REVIEW = "NON_MATERIAL_OVERLAP_MANUAL_REVIEW"
    UNRESOLVED_MISSING_MANDATORY_SOURCE = "UNRESOLVED_MISSING_MANDATORY_SOURCE"
    CONTRADICTORY_SOURCE_MANUAL_REVIEW = "CONTRADICTORY_SOURCE_MANUAL_REVIEW"


class SourceClass(StrEnum):
    AUTHORITATIVE = "AUTHORITATIVE"
    OFFICIAL_INDICATIVE = "OFFICIAL_INDICATIVE"
    MARKET = "MARKET"
    ANALYST_DERIVED = "ANALYST_DERIVED"
    MACHINE_ASSISTIVE = "MACHINE_ASSISTIVE"


class EvidencePolarity(StrEnum):
    FOR = "FOR"
    AGAINST = "AGAINST"
    UNKNOWN = "UNKNOWN"


class EvidenceImportance(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class VerifiedStatus(StrEnum):
    VERIFIED = "VERIFIED"
    UNVERIFIED = "UNVERIFIED"
    ANALYST_VERIFIED = "ANALYST_VERIFIED"


class BaselinePackStatus(StrEnum):
    DRAFT = "DRAFT"
    PILOT_READY = "PILOT_READY"
    SIGNED_OFF = "SIGNED_OFF"
    STALE = "STALE"


class ProposalForm(StrEnum):
    INFILL = "INFILL"
    REDEVELOPMENT = "REDEVELOPMENT"
    BROWNFIELD_REUSE = "BROWNFIELD_REUSE"
    BACKLAND = "BACKLAND"
    AIRSPACE = "AIRSPACE"


class ScenarioSource(StrEnum):
    AUTO = "AUTO"
    ANALYST = "ANALYST"
    IMPORTED = "IMPORTED"


class ScenarioStatus(StrEnum):
    SUGGESTED = "SUGGESTED"
    AUTO_CONFIRMED = "AUTO_CONFIRMED"
    ANALYST_CONFIRMED = "ANALYST_CONFIRMED"
    ANALYST_REQUIRED = "ANALYST_REQUIRED"
    REJECTED = "REJECTED"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"


class AssessmentRunState(StrEnum):
    PENDING = "PENDING"
    BUILDING_FEATURES = "BUILDING_FEATURES"
    BUILDING_COMPARABLES = "BUILDING_COMPARABLES"
    READY = "READY"
    FAILED = "FAILED"


class EstimateStatus(StrEnum):
    NONE = "NONE"
    ESTIMATE_AVAILABLE = "ESTIMATE_AVAILABLE"
    ESTIMATE_AVAILABLE_MANUAL_REVIEW_REQUIRED = (
        "ESTIMATE_AVAILABLE_MANUAL_REVIEW_REQUIRED"
    )
    RANK_ONLY = "RANK_ONLY"


class ReviewStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    REQUIRED = "REQUIRED"
    COMPLETED = "COMPLETED"


class EstimateQuality(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class HistoricalLabelClass(StrEnum):
    POSITIVE = "POSITIVE"
    NEGATIVE = "NEGATIVE"
    EXCLUDED = "EXCLUDED"
    CENSORED = "CENSORED"


class HistoricalLabelDecision(StrEnum):
    APPROVE = "APPROVE"
    CONDITIONAL_APPROVE = "CONDITIONAL_APPROVE"
    RESOLVE_TO_GRANT = "RESOLVE_TO_GRANT"
    REFUSE = "REFUSE"
    WITHDRAWN = "WITHDRAWN"
    INVALID = "INVALID"
    UNDETERMINED = "UNDETERMINED"
    DUPLICATE = "DUPLICATE"
    ADMINISTRATIVE = "ADMINISTRATIVE"
    APPEAL_ONLY = "APPEAL_ONLY"
    NON_RELEVANT = "NON_RELEVANT"


class ComparableOutcome(StrEnum):
    APPROVED = "APPROVED"
    REFUSED = "REFUSED"


class GoldSetReviewStatus(StrEnum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    EXCLUDED = "EXCLUDED"


class ReleaseChannel(StrEnum):
    HIDDEN = "HIDDEN"


class ModelReleaseStatus(StrEnum):
    NOT_READY = "NOT_READY"
    VALIDATED = "VALIDATED"
    ACTIVE = "ACTIVE"
    RETIRED = "RETIRED"


class CalibrationMethod(StrEnum):
    NONE = "NONE"
    PLATT = "PLATT"


class AppRoleName(StrEnum):
    ANALYST = "analyst"
    REVIEWER = "reviewer"
    ADMIN = "admin"


class StorageBackend(StrEnum):
    LOCAL = "local"
    SUPABASE = "supabase"


class ValuationRunState(StrEnum):
    PENDING = "PENDING"
    READY = "READY"
    FAILED = "FAILED"


class ValuationQuality(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class MarketLandCompSourceType(StrEnum):
    PERMISSIONED_LISTING = "PERMISSIONED_LISTING"
    AUCTION = "AUCTION"
    ANALYST_BENCHMARK = "ANALYST_BENCHMARK"


class OpportunityBand(StrEnum):
    BAND_A = "Band A"
    BAND_B = "Band B"
    BAND_C = "Band C"
    BAND_D = "Band D"
    HOLD = "Hold"
